dev	tun
port	1194
remote	<remote-server IP or FQDN>
mode	p2p
#client
#
#
# Certificates
ca      /etc/pki/tls/certs/P2P-CA.crt
cert    /etc/pki/tls/certs/P2P-Client.crt
key     /etc/pki/tls/private/P2P-Client.pem
#
remote-cert-tls	server
#
#
tls-client
#   IPv4
proto	udp
# Network: matching the server's ifconfig
ifconfig    192.168.200.2 192.168.200.1
# Routing (Assuming server LAN is 192.168.1.0/24)
route	    192.168.200.0 255.255.255.0
#
#   IPv6
proto		udp6
ifconfig-ipv6	<prefix>::2 <prefix>::1
#
#
# Security
cipher	    AES-256-GCM
auth	    SHA256
auth-nocache
keepalive   10 60
ping-timer-rem
persist-tun
user	    nobody
group	    nobody
daemon
#
#
# Logging
verb	    3
